/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SfwWizardDefineInterfacesR11.java
 *
 * Created on Jun 27, 2013, 4:10:26 PM
 */
package sfwinstaladorscript.oracleinstallation.components_interfaces_define;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author jopaulo
 */
public class SfwWizardDefineInterfacesR11 extends javax.swing.JPanel {

    /** Creates new form SfwWizardDefineInterfacesR11 */
    public SfwWizardDefineInterfacesR11() {
        initComponents();
        this.jTextDBLINK.requestFocus();
    }

    /**
     * Valida se existe campos em branco
     * @return 
     */
    public boolean validaCampos() {
        boolean valida = true;
        if (this.jTextDBLINK.getText().equals("")) {
            valida = false;
        }
        return valida;
    }

    /**
     * 
     * @param valores
     * @return 
     */
    public boolean populaCampos(List<SfwOracleDefineInterface> valores) {

        for (int i = 0; i < valores.size(); i++) {
            SfwOracleDefineInterface sfwOracleDefineInterface = valores.get(i);
            if (sfwOracleDefineInterface.getNome().equals("IT_R11")) {
                this.jTextDBLINK.setText(sfwOracleDefineInterface.getUser());
            }
        }
        return true;
    }

    /**
     * 
     * @return 
     */
    public List<SfwOracleDefineInterface> retornaUsuariosDefine() {
        List<SfwOracleDefineInterface> oracle_defines = new ArrayList<SfwOracleDefineInterface>();

        SfwOracleDefineInterface DBLINK = new SfwOracleDefineInterface();
        DBLINK.setNome("IT_R11");
        DBLINK.setUser(this.jTextDBLINK.getText());
        DBLINK.setPass(this.jTextDBLINK.getText());
        DBLINK.setTns(this.jTextDBLINK.getText());
        oracle_defines.add(DBLINK);

        return oracle_defines;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextDBLINK = new javax.swing.JTextField();

        setName("Form"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sfwinstaladorscript.SfwInstaladorScriptApp.class).getContext().getResourceMap(SfwWizardDefineInterfacesR11.class);
        jLabel8.setFont(resourceMap.getFont("jLabel8.font")); // NOI18N
        jLabel8.setForeground(resourceMap.getColor("jLabel8.foreground")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jTextDBLINK.setName("jTextDBLINK"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(446, 446, 446))
                    .addComponent(jTextDBLINK, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextDBLINK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextDBLINK;
    // End of variables declaration//GEN-END:variables
}
