/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * sfwValidatorLine.java
 *
 * Created on Oct 22, 2019, 11:13:06 AM
 */
package sfwinstaladorscript.validadorIT;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author U6068136
 */
public class sfwValidatorLine extends javax.swing.JPanel {
    
    /** Creates new form sfwValidatorLine */
    public sfwValidatorLine() {
        initComponents(); 
    }

    /** Creates new form sfwValidatorLine */
    public sfwValidatorLine(String label, String buttonStatus, final String executionLog) {
        initComponents();
        
        JButton jButton1 = new JButton();
        jButton1.setName(buttonStatus); // NOI18N
        
        //Desabilita botao quanto retorno é OK
        if(buttonStatus.equals("OK")){
            jButton1.setEnabled(false);
            jButton1.setBackground(Color.green);

        }else{
            jButton1.setBackground(Color.red);

        }   
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 417, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        //
        jButton1.setText(buttonStatus);
        jButton1.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {
                
                JTextArea textArea = new JTextArea(executionLog);
                textArea.setColumns(100);
                textArea.setLineWrap(true);
                textArea.setWrapStyleWord(true);
    
    
               JOptionPane.showMessageDialog(new JFrame(),
                       new JScrollPane(textArea),
                       "Log",
                       JOptionPane.ERROR_MESSAGE);

        }
        });
        
        //
        jLabel1.setText(label);
        
        //TODO use SqlFileName to button action to read log
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(461, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
